### PR TITLE
Feature/add cc by

### PR DESCRIPTION
**Pull request by chienleng**
Updates:
* added CC-BY icon(s) to website footer and About page with a tooltip and link to CC-BY licence page
* added CC-BY icons to export PNG footer

### CODE REVIEW

**Comment by chienleng** [comment]
if you want to review the design and see a preview, you should see this below the last comment.:
Screenshot 2023-06-09 at 5 58 23 pm

click on the Show Environments and click on 'View deployment' button should take you to the preview of this PR.
Screenshot 2023-06-09 at 5 58 29 pm

----
You can submit your review by going to the `Files Changed` tab, then click on 'Review Changes' and submit your review. 
Screenshot 2023-06-09 at 6 03 47 pm

Screenshot 2023-06-09 at 6 04 18 pm

**Comment by chienleng** [comment]
you could also look at each line change and add your comment if you are reviewing the code. I think for now let's start with the design. 

Just add your notes into the comments or suggestions. And approve via the 'Review changes' section if you are happy with it.

**Review by simonhac — APPROVED** [review]
looks great @chienleng!

**Comment by simonhac** [comment]
thank you for the great instructions @chienleng. much appreciated.

**Pull request merged**
